-- [[ModuleScript] AchievementConfig (ref: RBXFD5CA6C99CE8432DB25544EFF81486CB)]]
return {
	{
		id = "first_serve",
		name = "First Plate",
		desc = "Serve your first guest",
		icon = "🍽️",
		metric = "guestsServed",
		goal = 1,
	},
	{
		id = "ten_serves",
		name = "Getting Hungry",
		desc = "Serve 10 guests",
		icon = "🥘",
		metric = "guestsServed",
		goal = 10,
	},
	{
		id = "fifty_serves",
		name = "Restaurant Regular",
		desc = "Serve 50 guests",
		icon = "🍱",
		metric = "guestsServed",
		goal = 50,
	},
	{
		id = "hundred_serves",
		name = "Beloved Chef",
		desc = "Serve 100 guests",
		icon = "👨‍🍳",
		metric = "guestsServed",
		goal = 100,
	},
	{
		id = "first_perfect",
		name = "Perfect Timing",
		desc = "Cook your first perfect dish",
		icon = "⏱️",
		metric = "perfectCooks",
		goal = 1,
	},
	{
		id = "ten_perfects",
		name = "On Beat",
		desc = "Cook 10 perfect dishes",
		icon = "🎯",
		metric = "perfectCooks",
		goal = 10,
	},
	{
		id = "fifty_perfects",
		name = "Master of Timing",
		desc = "Cook 50 perfect dishes",
		icon = "💫",
		metric = "perfectCooks",
		goal = 50,
	},
	{
		id = "combo_5",
		name = "Combo Starter",
		desc = "Hit a 5-combo",
		icon = "🔥",
		metric = "maxCombo",
		goal = 5,
	},
	{
		id = "combo_10",
		name = "Streak King",
		desc = "Hit a 10-combo",
		icon = "⚡",
		metric = "maxCombo",
		goal = 10,
	},
	{
		id = "combo_15",
		name = "Untouchable",
		desc = "Hit a 15-combo",
		icon = "💥",
		metric = "maxCombo",
		goal = 15,
	},
	{
		id = "gather_50",
		name = "Gatherer",
		desc = "Gather 50 items",
		icon = "🌾",
		metric = "totalGather",
		goal = 50,
	},
	{
		id = "gather_500",
		name = "Resourceful",
		desc = "Gather 500 items",
		icon = "🌿",
		metric = "totalGather",
		goal = 500,
	},
	{
		id = "gold_100",
		name = "First Hundred",
		desc = "Earn 100 gold",
		icon = "💰",
		metric = "totalGold",
		goal = 100,
	},
	{
		id = "gold_1000",
		name = "Coin Collector",
		desc = "Earn 1000 gold",
		icon = "🪙",
		metric = "totalGold",
		goal = 1000,
	},
	{
		id = "gold_10000",
		name = "Wealthy Cook",
		desc = "Earn 10000 gold",
		icon = "💎",
		metric = "totalGold",
		goal = 10000,
	},
	{
		id = "lvl_5",
		name = "Sous Chef",
		desc = "Reach Chef Level 5",
		icon = "🍳",
		metric = "chefLevel",
		goal = 5,
	},
	{
		id = "lvl_10",
		name = "Chef",
		desc = "Reach Chef Level 10",
		icon = "👨‍🍳",
		metric = "chefLevel",
		goal = 10,
	},
	{
		id = "lvl_20",
		name = "Head Chef",
		desc = "Reach Chef Level 20",
		icon = "⭐",
		metric = "chefLevel",
		goal = 20,
	},
	{
		id = "lvl_30",
		name = "Grandmaster",
		desc = "Reach Chef Level 30",
		icon = "👑",
		metric = "chefLevel",
		goal = 30,
	},
	{
		id = "regular_5",
		name = "Local Favorite",
		desc = "Earn rep 5 with one guest",
		icon = "🤝",
		metric = "maxRep",
		goal = 5,
	},
	{
		id = "regular_20",
		name = "Best Friends",
		desc = "Earn rep 20 with one guest",
		icon = "💞",
		metric = "maxRep",
		goal = 20,
	},
	{
		id = "mastery_1",
		name = "Recipe Mastered",
		desc = "Master a recipe (level 5)",
		icon = "📖",
		metric = "maxMastery",
		goal = 5,
	},
	{
		id = "mastery_3",
		name = "Versatile Cook",
		desc = "Master 3 recipes",
		icon = "📚",
		metric = "masteredCount",
		goal = 3,
	},
	{
		id = "tool_t2",
		name = "Tool Smith",
		desc = "Upgrade a tool to Tier 2",
		icon = "🔨",
		metric = "maxToolTier",
		goal = 2,
	},
	{
		id = "tool_t3",
		name = "Tool Master",
		desc = "Upgrade a tool to Tier 3",
		icon = "⚒️",
		metric = "maxToolTier",
		goal = 3,
	},
	{
		id = "daily_3",
		name = "Coming Back",
		desc = "Log in 3 days in a row",
		icon = "📅",
		metric = "loginStreak",
		goal = 3,
	},
	{
		id = "daily_7",
		name = "Devoted",
		desc = "Log in 7 days in a row",
		icon = "🗓️",
		metric = "loginStreak",
		goal = 7,
	},
	{
		id = "powerup_first",
		name = "Powered Up",
		desc = "Use your first power-up",
		icon = "✨",
		metric = "powerupsUsed",
		goal = 1,
	},
	{
		id = "daily_quest_first",
		name = "Daily Doer",
		desc = "Finish a daily quest",
		icon = "📋",
		metric = "dailyQuestsDone",
		goal = 1,
	},
	{
		id = "daily_quest_10",
		name = "Routine Master",
		desc = "Finish 10 daily quests",
		icon = "🏆",
		metric = "dailyQuestsDone",
		goal = 10,
	},
}
