--!strict
-- DisclaimerConfig: in-game AI chat disclosure copy (Roblox generative AI policy).

local DisclaimerConfig = {}

DisclaimerConfig.title = "AI Mentor Chat"

DisclaimerConfig.body = [[This game includes optional AI-powered mentor chat (Zundapal & Master Chef Zunda).

• Replies are generated by a third-party AI and may be wrong or inappropriate.
• Do not share personal information (real name, address, phone, school).
• Chat is filtered but not perfect — play with a parent or guardian if you are under 13.
• Your display name, filtered message, and basic gameplay context are sent to the AI provider for this session only.
• Chat history is not saved after you leave the game.

You can always use scripted dialogue instead of free chat.]]

DisclaimerConfig.acceptLabel = "I understand — enable AI chat"
DisclaimerConfig.declineLabel = "Use scripted dialogue only"

return DisclaimerConfig
