--!strict
-- [[ModuleScript] ArchitectureVariants]
-- Auto-generated by mesh_auto_mapper.py
-- Building and prop meshes from Kenney Architecture Kit (CC0, kenney.nl)

local ArchitectureVariants = {
	["Lantern"] = {
		["Lantern"] = { meshes = { ["Lantern"] = "rbxassetid://9854046603" } },
	},
}

return ArchitectureVariants