--!strict
-- [[ModuleScript] NPCConfig]
-- Auto-generated by mesh_auto_mapper.py
-- Guest NPC models from Kenney Mini Characters (CC0, kenney.nl)
-- See CREDITS.md for full attribution

local NPCConfig = {}

NPCConfig.guestTemplates = {
}

NPCConfig.companionTemplates = {
	Zundapal = { modelId = "", scale = 0.5, followSpeed = 8, sparkleEffect = "", buff = nil, price = 0 },
}

NPCConfig.guestSpawnDefaults = {
	spawnInterval = 15,
	maxGuests = 8,
	timeoutDuration = 120,
	maxQueueDistance = 24,
}

NPCConfig.spawnPoints = {
	Vector3.new(188, -518, -415),
	Vector3.new(196, -518, -415),
	Vector3.new(204, -518, -415),
	Vector3.new(212, -518, -415),
}

return NPCConfig