--!strict
-- [[ModuleScript] NPCConfig]
-- Auto-generated by mesh_auto_mapper.py
-- Guest NPC models from Kenney Mini Characters (CC0, kenney.nl)
-- See CREDITS.md for full attribution

local NPCConfig = {}

NPCConfig.guestTemplates = {
}

NPCConfig.companionTemplates = {
	zundamon = { modelId = "rbxassetid://121481310719137", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = nil, price = 0 },
	zundacat = { modelId = "rbxassetid://101663144452966", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = nil, price = 0 },
	zundabunny = { modelId = "rbxassetid://76425192775041", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = nil, price = 0 },
	tantanmon = { modelId = "rbxassetid://107150527246774", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = nil, price = 0 },
	ankomon = { modelId = "rbxassetid://110290651922538", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = { stat = "gold", magnitude = 0.15 }, price = 500 },
	cardamon = { modelId = "rbxassetid://91041813069462", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = { stat = "perfect_window", magnitude = 0.30 }, price = 500 },
	antimon = { modelId = "rbxassetid://94125444857929", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = { stat = "extra_drop", magnitude = 0.20 }, price = 500 },
	sakuradamon = { modelId = "rbxassetid://128478553136178", scale = 0.5, followSpeed = 8, sparkleEffect = "rbxassetid://241685484", buff = { stat = "xp", magnitude = 0.25 }, price = 500 },
}

NPCConfig.guestSpawnDefaults = {
	spawnInterval = 15,
	maxGuests = 8,
	timeoutDuration = 120,
	maxQueueDistance = 24,
}

NPCConfig.spawnPoints = {
	Vector3.new(188, -518, -415),
	Vector3.new(196, -518, -415),
	Vector3.new(204, -518, -415),
	Vector3.new(212, -518, -415),
}

function NPCConfig.getQualityMultiplier(quality)
	if quality == "perfect" then
		return 1.5
	elseif quality == "great" then
		return 1.2
	end
	return 1.0
end

return NPCConfig