--!strict
-- [[ModuleScript] MeshAssets]
-- Auto-generated by mesh_auto_mapper.py from workspace meshes
-- See CREDITS.md for full attribution

return {
	meshes = {
		-- Harvest Nodes

		-- Environment Props
		["Bush"] = {
			["bush"] = "rbxassetid://71267543570887",
		},
		["Lantern"] = {
			["Lantern"] = "rbxassetid://9854046603",
		},
		["Neon"] = {
			["neon heart"] = "rbxassetid://601198887",
		},
	},
}