-- [[ModuleScript] QuestConfig (ref: RBXF6CB94E09956482FB9EF70B219DFF3C7)]]
-- QuestConfig: Data-driven quest definitions
-- Persisted by QuestManager; modified by admin menus

local QuestConfig = {
	quests = {
		-- Example quest structure:
		-- {
		--   id = "quest_1",
		--   name = "First Guests",
		--   description = "Serve 5 guests at the kitchen",
		--   icon = "🍽️",
		--   type = "serve", -- serve, cook, gather, earn_gold
		--   target = 5, -- guests to serve
		--   rewards = {
		--     gold = 50,
		--     tier_points = 10,
		--     items = {}
		--   },
		--   difficulty = 1 -- 1-5 scale
		-- }
	},
	
	-- Default quests to initialize on player join
	default_quests = {
		{
			id = "quest_welcome_1",
			name = "Welcome to the Kitchen",
			description = "Serve your first guest",
			icon = "🍽️",
			type = "serve",
			target = 1,
			rewards = {
				gold = 25,
				tier_points = 5,
				items = {}
			},
			difficulty = 1
		},
		{
			id = "quest_cafe_master",
			name = "Café Master",
			description = "Serve 10 guests",
			icon = "⭐",
			type = "serve",
			target = 10,
			rewards = {
				gold = 100,
				tier_points = 20,
				items = {}
			},
			difficulty = 2
		},
		-- NEW ZUNDA-THEMED QUESTS
		{
			id = "quest_zunda_pea_collector",
			name = "Zunda Pea Collector",
			description = "Gather 10 Zunda Peas from the garden",
			icon = "🫛",
			type = "gather",
			target = 10,
			target_item = "Zunda Pea",
			rewards = {
				gold = 50,
				tier_points = 10,
				items = {"Zunda Mochi"}
			},
			difficulty = 1
		},
		{
			id = "quest_edamame_harvest",
			name = "Edamame Harvest",
			description = "Collect 5 Edamame Pods",
			icon = "🌿",
			type = "gather",
			target = 5,
			target_item = "Edamame Pod",
			rewards = {
				gold = 75,
				tier_points = 15,
				items = {}
			},
			difficulty = 2
		},
		{
			id = "quest_zunda_mochi_master",
			name = "Zunda Mochi Master",
			description = "Craft 3 Zunda Mochi",
			icon = "🍡",
			type = "cook",
			target = 3,
			target_item = "Zunda Mochi",
			rewards = {
				gold = 150,
				tier_points = 30,
				items = {"Sweet Pea"}
			},
			difficulty = 3
		},
		{
			id = "quest_pea_flower_garden",
			name = "Pea Flower Garden",
			description = "Find 8 Pea Flowers",
			icon = "🌸",
			type = "gather",
			target = 8,
			target_item = "Pea Flower",
			rewards = {
				gold = 100,
				tier_points = 20,
				items = {}
			},
			difficulty = 2
		},
		{
			id = "quest_zunda_paradise",
			name = "Zunda Paradise Chef",
			description = "Cook the legendary Zunda Paradise dish",
			icon = "✨",
			type = "cook",
			target = 1,
			target_item = "Zunda Paradise",
			rewards = {
				gold = 500,
				tier_points = 100,
				items = {}
			},
			difficulty = 5
		},

		-- ─────────────────────────────────────────────────────
		-- NEW QUEST BATCH — gathering, cooking, serving, exploration, mastery
		-- ─────────────────────────────────────────────────────

		-- GATHERING quests
		{
			id = "quest_apple_picker",
			name = "Apple Picker",
			description = "Pick 20 apples from the orchard",
			icon = "\u{1F34E}",
			type = "gather",
			target = 20,
			target_item = "Apple",
			rewards = { gold = 80, tier_points = 15, items = {} },
			difficulty = 1
		},
		{
			id = "quest_wheat_field",
			name = "Wheat Field Worker",
			description = "Harvest 30 wheat",
			icon = "\u{1F33E}",
			type = "gather",
			target = 30,
			target_item = "Wheat",
			rewards = { gold = 60, tier_points = 12, items = {} },
			difficulty = 1
		},
		{
			id = "quest_sweet_pea_search",
			name = "Sweet Pea Search",
			description = "Find 12 Sweet Peas in the garden",
			icon = "\u{1FAD8}",
			type = "gather",
			target = 12,
			target_item = "Sweet Pea",
			rewards = { gold = 120, tier_points = 20, items = {} },
			difficulty = 2
		},
		{
			id = "quest_zunda_leaf_walk",
			name = "Leafy Walk",
			description = "Collect 15 Zunda Leaves",
			icon = "\u{1F343}",
			type = "gather",
			target = 15,
			target_item = "Zunda Leaf",
			rewards = { gold = 90, tier_points = 18, items = {} },
			difficulty = 2
		},
		{
			id = "quest_gold_prospector",
			name = "Gold Prospector",
			description = "Mine 5 nuggets of Gold from the rocks",
			icon = "\u{1F4B0}",
			type = "gather",
			target = 5,
			target_item = "Gold",
			rewards = { gold = 200, tier_points = 30, items = {} },
			difficulty = 3
		},

		-- COOKING quests
		{
			id = "quest_bread_baker",
			name = "Bread Baker",
			description = "Bake 5 loaves of Bread",
			icon = "\u{1F35E}",
			type = "cook",
			target = 5,
			target_item = "Bread",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 1
		},
		{
			id = "quest_apple_pie_party",
			name = "Apple Pie Party",
			description = "Cook 4 Apple Pies",
			icon = "\u{1F967}",
			type = "cook",
			target = 4,
			target_item = "Apple Pie",
			rewards = { gold = 160, tier_points = 24, items = {} },
			difficulty = 2
		},
		{
			id = "quest_pea_flower_tea",
			name = "Tea Time",
			description = "Brew 3 cups of Pea Flower Tea",
			icon = "\u{1F375}",
			type = "cook",
			target = 3,
			target_item = "Pea Flower Tea",
			rewards = { gold = 180, tier_points = 28, items = {} },
			difficulty = 2
		},
		{
			id = "quest_royal_stew",
			name = "Royal Cuisine",
			description = "Prepare 2 servings of Royal Stew",
			icon = "\u{1F35B}",
			type = "cook",
			target = 2,
			target_item = "Royal Stew",
			rewards = { gold = 240, tier_points = 35, items = {} },
			difficulty = 3
		},
		{
			id = "quest_perfect_cook_streak",
			name = "Perfect Cook Streak",
			description = "Land 5 PERFECT timing cooks",
			icon = "\u{2728}",
			type = "cook_perfect",
			target = 5,
			rewards = { gold = 300, tier_points = 45, items = {} },
			difficulty = 3
		},

		-- SERVING / GUEST quests
		{
			id = "quest_breakfast_rush",
			name = "Breakfast Rush",
			description = "Serve 3 guests before noon",
			icon = "\u{1F373}",
			type = "serve",
			target = 3,
			rewards = { gold = 90, tier_points = 18, items = {} },
			difficulty = 1
		},
		{
			id = "quest_dinner_rush",
			name = "Dinner Rush",
			description = "Serve 15 guests in a day",
			icon = "\u{1F37D}",
			type = "serve",
			target = 15,
			rewards = { gold = 220, tier_points = 32, items = {} },
			difficulty = 3
		},
		{
			id = "quest_legendary_host",
			name = "Legendary Host",
			description = "Serve 50 guests total",
			icon = "\u{1F451}",
			type = "serve",
			target = 50,
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 4
		},

		-- ECONOMY quests
		{
			id = "quest_first_100_gold",
			name = "First Coins",
			description = "Earn 100 gold total",
			icon = "\u{1FA99}",
			type = "earn_gold",
			target = 100,
			rewards = { gold = 25, tier_points = 8, items = {} },
			difficulty = 1
		},
		{
			id = "quest_gold_hoard",
			name = "Gold Hoard",
			description = "Accumulate 1,000 gold",
			icon = "\u{1F4B0}",
			type = "earn_gold",
			target = 1000,
			rewards = { gold = 150, tier_points = 35, items = {} },
			difficulty = 3
		},
		{
			id = "quest_master_economist",
			name = "Master Economist",
			description = "Accumulate 5,000 gold",
			icon = "\u{1F4B5}",
			type = "earn_gold",
			target = 5000,
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 5
		},

		-- EXPLORATION quests (uses zone visit / building entry)
		{
			id = "quest_visit_kitchen",
			name = "Find the Kitchen",
			description = "Visit the Kitchen Workshop",
			icon = "\u{1F373}",
			type = "visit_zone",
			target = 1,
			target_zone = "Kitchen",
			rewards = { gold = 30, tier_points = 5, items = {} },
			difficulty = 1
		},
		{
			id = "quest_visit_pagoda",
			name = "Peaceful Pilgrimage",
			description = "Visit the Pagoda in the Zen Garden",
			icon = "\u{26E9}",
			type = "visit_zone",
			target = 1,
			target_zone = "Pagoda",
			rewards = { gold = 60, tier_points = 10, items = {} },
			difficulty = 1
		},
		{
			id = "quest_visit_ruins",
			name = "Ancient Whispers",
			description = "Discover the Ancient Ruins",
			icon = "\u{1F3DB}",
			type = "visit_zone",
			target = 1,
			target_zone = "AncientRuins",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 2
		},
		{
			id = "quest_visit_all_zones",
			name = "World Tour",
			description = "Visit every zone at least once",
			icon = "\u{1F30D}",
			type = "visit_zones_unique",
			target = 5,
			rewards = { gold = 350, tier_points = 55, items = {} },
			difficulty = 3
		},

		-- COMPANION / SOCIAL quests
		{
			id = "quest_chat_with_zundapal",
			name = "Best Friends",
			description = "Chat with Zundapal 5 times",
			icon = "\u{1F361}",
			type = "companion_chat",
			target = 5,
			rewards = { gold = 50, tier_points = 12, items = {} },
			difficulty = 1
		},
		{
			id = "quest_meet_elder",
			name = "Wisdom of the Elder",
			description = "Speak with the Village Elder",
			icon = "\u{1F3EE}",
			type = "npc_chat",
			target = 1,
			target_npc = "Elder",
			rewards = { gold = 75, tier_points = 14, items = {} },
			difficulty = 2
		},

		-- MASTERY quests (long-running)
		{
			id = "quest_recipe_collector",
			name = "Recipe Collector",
			description = "Cook every recipe at least once",
			icon = "📖",
			type = "cook_unique",
			target = 12,
			rewards = { gold = 600, tier_points = 90, items = {} },
			difficulty = 4,
			subtext = "The Chef's Testament demands every dish be tasted. You've mastered the basics — now hunt down every recipe in existence. Each one tells a story. Each one earns a star.",
			npc_dialogue = { speaker = "chef", lines = { "You think you know cooking? HA. Cook EVERYTHING. Then come back and I MIGHT be impressed." } },
		},
		{
			id = "quest_zunda_grand_master",
			name = "Zunda Grand Master",
			description = "Cook every Zunda-themed recipe",
			icon = "🥞",
			type = "cook_unique_zunda",
			target = 6,
			rewards = { gold = 700, tier_points = 120, items = {} },
			difficulty = 5,
			subtext = "The Zunda spirits have been watching. Every pea you've mashed, every mochi you've pounded — it all leads here. Cook every Zunda dish and claim the title of GRAND MASTER.",
			npc_dialogue = { speaker = "zundapal", lines = { "YOU'RE SO CLOSE I CAN TASTE IT!!! Literally. I ate a pea. But STILL. COOK ALL THE THINGS 🍡🔥", "ZUNDA PARADISE is the final test. 15 Zunda Peas!!! 10 Edamame!!! 5 Sweet Peas!!! 3 Pea Flowers!!! GO!!! GO!!! GO!!!" } },
			chain_id = "zunda_legend",
			chain_step = 3,
		},

		-- ════════════════════════════════════════════════════════════════
		-- NEW QUEST BATCH v2 — Chains, subtext, companion & seasonal
		-- ════════════════════════════════════════════════════════════════

		-- ── CHAIN: "The Great Zunda Hunt" (gathering) ──────────────────
		{
			id = "quest_zunda_hunt_1",
			name = "Zunda Pea Hunting",
			description = "Gather 15 Zunda Peas",
			icon = "🫛",
			type = "gather",
			target = 15,
			target_item = "Zunda Pea",
			rewards = { gold = 80, tier_points = 15, items = {} },
			difficulty = 2,
			subtext = "The village elder says the first Zunda Peas were discovered by a chef who chased a rainbow into a field. 'Follow the glint,' he said. 'Stampede the peas.' Now it's your turn.",
			chain_id = "great_zunda_hunt",
			chain_step = 1,
		},
		{
			id = "quest_zunda_hunt_2",
			name = "Edamame Expedition",
			description = "Collect 10 Edamame Pods",
			icon = "🌿",
			type = "gather",
			target = 10,
			target_item = "Edamame Pod",
			rewards = { gold = 120, tier_points = 20, items = { "Sweet Pea" } },
			difficulty = 2,
			subtext = "Deep in the Edamame Thicket, the pods hang like green lanterns. Legend says they only reveal themselves to those who approach with a full belly and an empty mind. Also, you need 10 of them.",
			chain_id = "great_zunda_hunt",
			chain_step = 2,
		},
		{
			id = "quest_zunda_hunt_3",
			name = "Pea Flower Pilgrimage",
			description = "Find 12 Pea Flowers",
			icon = "🌸",
			type = "gather",
			target = 12,
			target_item = "Pea Flower",
			rewards = { gold = 160, tier_points = 28, items = { "Pea Flower Tea" } },
			difficulty = 3,
			subtext = "The Pea Flowers bloom only where a Zunda chef once wept tears of joy. Follow the scent of crushed petals and distant happiness. Each flower you pick whispers a recipe from the Old Kitchen.",
			npc_dialogue = { speaker = "elder", lines = { "Ah, the Pea Flower Pilgrimage... I remember my first bloom. The flowers sing, you know. Not with words — with FLAVOR. Collect 12 and the path forward will reveal itself." } },
			chain_id = "great_zunda_hunt",
			chain_step = 3,
		},
		{
			id = "quest_zunda_hunt_4",
			name = "The Great Zunda Hunt",
			description = "Gather every Zunda ingredient at least once",
			icon = "🏆",
			type = "gather_unique",
			target = 9,
			rewards = { gold = 400, tier_points = 60, items = { "Zunda Paradise" } },
			difficulty = 4,
			subtext = "You've tasted the first fruits. NOW COMES THE HUNT. Zunda Pea. Edamame Pod. Sweet Pea. Pea Flower. Zunda Flower. Zunda Berry. Zunda Mushroom. Zunda Root. Zunda Leaf. COLLECT THEM ALL. The Zunda spirits demand tribute.",
			npc_dialogue = { speaker = "zundapal", lines = { "THE GREAT HUNT!!! I'M SHAKING!!! 🫛✨", "Every Zunda ingredient has a spirit inside. If you gather ALL 9 types, they'll COMBINE into something LEGENDARY. I'M NOT KIDDING. I SAW IT IN A DREAM. 🔥🔥🔥" } },
			chain_id = "great_zunda_hunt",
			chain_step = 4,
		},

		-- ── CHAIN: "Culinary Ascension" (cooking) ─────────────────────
		{
			id = "quest_culinary_1",
			name = "First Loaf",
			description = "Bake 3 loaves of Bread",
			icon = "🍞",
			type = "cook",
			target = 3,
			target_item = "Bread",
			rewards = { gold = 40, tier_points = 10, items = {} },
			difficulty = 1,
			subtext = "Every master chef started with bread. The Zunda monks believed the first loaf teaches patience, heat control, and the importance of NOT setting the kitchen on fire. Three loaves. Simple. Pure. Begin.",
			chain_id = "culinary_ascension",
			chain_step = 1,
		},
		{
			id = "quest_culinary_2",
			name = "Pie Prodigy",
			description = "Bake 3 Apple Pies with great timing",
			icon = "🥧",
			type = "cook_quality",
			target = 3,
			target_item = "Apple Pie",
			quality = "great",
			rewards = { gold = 120, tier_points = 22, items = {} },
			difficulty = 2,
			subtext = "A good pie is edible. A GREAT pie is a STATEMENT. The Zunda elders say the perfect Apple Pie crust should be 'golden as sunrise, flaky as autumn leaves, and warm as a hug after a long day.' Three pies. Make them proud.",
			chain_id = "culinary_ascension",
			chain_step = 2,
		},
		{
			id = "quest_culinary_3",
			name = "Royal Preparation",
			description = "Cook Royal Stew twice",
			icon = "👑",
			type = "cook",
			target = 2,
			target_item = "Royal Stew",
			rewards = { gold = 200, tier_points = 30, items = {} },
			difficulty = 3,
			subtext = "Royal Stew is not a meal — it's a coronation. The recipe was passed down by the Zunda King himself, who insisted on GOLD in his stew because 'commoners eat from bowls. KINGS EAT FROM BOWLS OF WEALTH.' Two servings. Rule the kitchen.",
			npc_dialogue = { speaker = "chef", lines = { "Royal Stew, huh? Bold choice. Most beginners CRUMBLE under the pressure of cooking with actual GOLD ORE.", "But you... you have the Zunda glint in your eye. COOK IT. TASTE IT. BECOME IT." } },
			chain_id = "culinary_ascension",
			chain_step = 3,
		},
		{
			id = "quest_culinary_4",
			name = "Feast of Legends",
			description = "Cook 1 Ultimate Feast",
			icon = "🏛️",
			type = "cook",
			target = 1,
			target_item = "Ultimate Feast",
			rewards = { gold = 500, tier_points = 80, items = {} },
			difficulty = 4,
			subtext = "The Ultimate Feast is not on any menu. It IS the menu. The Zunda monks cooked it only during celestial alignments. 30 Wheat. 20 Apples. 5 Gold. This dish doesn't feed people — it INAUGURATES them. Cook it once. Be forever changed.",
			npc_dialogue = { speaker = "narrator", lines = { "[ The kitchen grows dark. The stove flickers. Somewhere, a pea rolls across the floor. ]", "[ A voice from the flames whispers: 'You dare to cook the FEAST?' ]" } },
			chain_id = "culinary_ascension",
			chain_step = 4,
		},
		{
			id = "quest_culinary_5",
			name = "Culinary Ascension",
			description = "Achieve a 10-cook perfect streak",
			icon = "🌟",
			type = "cook_perfect",
			target = 10,
			rewards = { gold = 800, tier_points = 120, items = { "Zundamon's Banquet" } },
			difficulty = 5,
			subtext = "The final trial. 10 PERFECT cooks in a row. No burnt edges. No undercooked centers. Just FLAWLESS CULINARY DOMINATION. The Zunda spirits will witness. The kitchen will SHAKE. AND YOU WILL RISE.",
			npc_dialogue = { speaker = "zundamon", lines = { "10 PERFECT COOKS!!! DO YOU HAVE ANY IDEA WHAT THAT MEANS?!?! 🔥🔥🔥", "THE KITCHEN ITSELF WILL RECOGNIZE YOU!!! THE STOVE WILL BOW!!! THE SPATULAS WILL SALUTE!!! GO GO GO!!!" } },
			chain_id = "culinary_ascension",
			chain_step = 5,
		},

		-- ── CHAIN: "Seasons of Flavor" (seasonal dishes) ──────────────
		{
			id = "quest_seasonal_summer",
			name = "Summer Breeze",
			description = "Cook 2 Seasonal Salads",
			icon = "☀️",
			type = "cook",
			target = 2,
			target_item = "Seasonal Salad",
			rewards = { gold = 130, tier_points = 22, items = { "Zunda Berry" } },
			difficulty = 2,
			subtext = "Summer in Zunda Village is a riot of color. The Zunda Berries are at their plumpest, the leaves are crisp, and the air smells of sunshine. The Seasonal Salad captures all of it in a bowl. Taste the sun.",
			npc_dialogue = { speaker = "sakuradamon", lines = { "🌸 SUMMER IS HERE AND THE BERRIES ARE SCREAMING TO BE PICKED!!!", "The Seasonal Salad is a celebration of light itself!!! 3 Zunda Berries + 2 Zunda Leaves = PERFECTION IN A BOWL!!!" } },
			chain_id = "seasons_of_flavor",
			chain_step = 1,
		},
		{
			id = "quest_seasonal_winter",
			name = "Winter Warmth",
			description = "Cook 2 Warm Winter Stews",
			icon = "❄️",
			type = "cook",
			target = 2,
			target_item = "Warm Winter Stew",
			rewards = { gold = 200, tier_points = 32, items = {} },
			difficulty = 3,
			subtext = "When snow blankets Zunda Village, the only cure is the Warm Winter Stew. Zunda Roots roasted for hours, Zunda Mushrooms simmered in gold-infused broth. One spoonful and you'll forget the cold exists. 'A hug in a bowl,' the elders call it.",
			npc_dialogue = { speaker = "elder", lines = { "The cold bites hard this season. But the stew... the stew bites BACK. ❄️🔥", "Zunda Roots from the permafrost. Zunda Mushrooms from the snow-kissed logs. And a pinch of gold because you're WORTH IT." } },
			chain_id = "seasons_of_flavor",
			chain_step = 2,
		},
		{
			id = "quest_seasonal_master",
			name = "Four Seasons Chef",
			description = "Cook every seasonal dish",
			icon = "🌍",
			type = "cook_unique_seasonal",
			target = 2,
			rewards = { gold = 350, tier_points = 50, items = { "Golden Harvest Platter" } },
			difficulty = 3,
			subtext = "Spring peas, summer berries, autumn roots, winter mushrooms. You've tasted each season. Now prove you can command them all. Cook every seasonal dish and become the Four Seasons Chef of Zunda Village.",
			chain_id = "seasons_of_flavor",
			chain_step = 3,
		},

		-- ── CHAIN: "Friend of All" (companion) ────────────────────────
		{
			id = "quest_friend_chat",
			name = "Hello Friend",
			description = "Chat with your companion 10 times",
			icon = "💬",
			type = "companion_chat",
			target = 10,
			rewards = { gold = 60, tier_points = 15, items = {} },
			difficulty = 1,
			subtext = "Your companion is more than a follower — they're your kitchen soulmate. Every chat deepens your bond. Who knows what secrets they'll share after 10 heart-to-hearts?",
			chain_id = "friend_of_all",
			chain_step = 1,
		},
		{
			id = "quest_friend_elder",
			name = "Elder's Wisdom",
			description = "Speak with the Village Elder 3 times",
			icon = "🏮",
			type = "npc_chat",
			target = 3,
			target_npc = "Elder",
			rewards = { gold = 100, tier_points = 18, items = {} },
			difficulty = 2,
			subtext = "The Village Elder has seen empires rise and fall on the strength of their stews. He carries the Old Knowledge. Three conversations might earn you a secret even the Zunda monks forgot.",
			npc_dialogue = { speaker = "elder", lines = { "You keep coming back. Good. Most lack the patience for an old man's rambling.", "But YOU... you have the Zunda hunger. Come, sit. I'll tell you about the GOLDEN PEA OF LEGEND... but only after three visits." } },
			chain_id = "friend_of_all",
			chain_step = 2,
		},
		{
			id = "quest_friend_all",
			name = "Friend of All",
			description = "Chat with every NPC in the village",
			icon = "🤝",
			type = "npc_chat_all",
			target = 5,
			rewards = { gold = 250, tier_points = 40, items = { "Antimon's Speed Soup" } },
			difficulty = 3,
			subtext = "Zunda Village is held together by its characters. The Chef. The Elder. The Whisper in the Ruins. Make yourself known to every soul who calls this place home. A kitchen is nothing without its community.",
			chain_id = "friend_of_all",
			chain_step = 3,
		},

		-- ── COMPANION-SPECIFIC QUESTS ─────────────────────────────────
		{
			id = "quest_ankomon_strength",
			name = "Ankomon's Trial of Protein",
			description = "Cook Ankomon's Protein Punch 3 times",
			icon = "💪",
			type = "cook",
			target = 3,
			target_item = "Ankomon's Protein Punch",
			rewards = { gold = 250, tier_points = 35, items = {} },
			difficulty = 3,
			subtext = "Ankomon challenges you to a test of PURE PROTEIN POWER. 'Each punch,' he says, 'is 5 Edamame Pods + 3 Zunda Peas + 1 Gold of pure RESPECT.' Cook it thrice. Prove your BEAN WORTHY.",
			npc_dialogue = { speaker = "ankomon", lines = { "🫘🥊 PROTEIN PUNCH!!! THIS ISN'T JUST FOOD IT'S A WORKOUT!!!", "COOK IT THREE TIMES AND I'LL ADMIT YOU HAVE BEAN SPIRIT!!! FAIL AND YOU'RE ON SOUP DUTY FOR A WEEK!!!" } },
		},
		{
			id = "quest_cardamon_zen",
			name = "Cardamon's Path of Patience",
			description = "Cook 5 dishes with GREAT quality or better",
			icon = "🧘",
			type = "cook_quality",
			target = 5,
			quality = "great",
			rewards = { gold = 200, tier_points = 30, items = { "Cardamon's Calm Cup" } },
			difficulty = 2,
			subtext = "Cardamon whispers: 'Speed means nothing. PRESENCE means everything.' Five dishes, each made with mindfulness and intent. Not rushed. Not forced. JUST. GREAT. Breathe in. Cook out.",
			npc_dialogue = { speaker = "cardamon", lines = { "🌿🍋 Patience... breathe... C O O K...", "Five great dishes. Not 'good'. GREAT. I'll know the difference. YOUR SOUL WILL KNOW THE DIFFERENCE." } },
		},
		{
			id = "quest_antimon_speed",
			name = "Antimon's Speed Trial",
			description = "Cook 3 dishes under 4 seconds each",
			icon = "⚡",
			type = "cook_speed",
			target = 3,
			max_cook_time = 4,
			rewards = { gold = 180, tier_points = 28, items = { "Antimon's Speed Soup" } },
			difficulty = 2,
			subtext = "Antimon vibrates with impatience. 'THE TIMING BAR IS NOT A SUGGESTION!!!' Three dishes. Under 4 seconds each. NO MISTAKES. SPEED IS FLAVOR. CHAOS IS TECHNIQUE.",
			npc_dialogue = { speaker = "antimon", lines = { "⚡💨 SPEED SPEED SPEED!!! THE TIMER IS YOUR BEST FRIEND AND WORST ENEMY!!!", "COOK LIKE THE WIND!!! 4 SECONDS!!! MAXIMUM!!!" } },
		},
		{
			id = "quest_sakuradamon_bloom",
			name = "Sakuradamon's Blossom Festival",
			description = "Cook 3 Sakuradamon's Blossom Bites",
			icon = "🌸",
			type = "cook",
			target = 3,
			target_item = "Sakuradamon's Blossom Bites",
			rewards = { gold = 280, tier_points = 38, items = {} },
			difficulty = 3,
			subtext = "Sakuradamon's petals glow brighter when her favorite dish is made. 'Blossom Bites,' she says, 'are not cooked — they're BLOOMED.' 4 Pea Flowers + 3 Zunda Berries. Each one a celebration of impermanent beauty.",
			npc_dialogue = { speaker = "sakuradamon", lines = { "🌸💥 THE BLOSSOMS ARE ALIGNED!!! IT'S FESTIVAL TIME!!!", "Each Blossom Bite captures a moment of pure spring joy. COOK THREE. LET THE PETALS FALL WHERE THEY MAY." } },
		},

		-- ── EXPLORATION QUESTS v2 ────────────────────────────────────
		{
			id = "quest_explore_garden",
			name = "Garden Secrets",
			description = "Find the hidden garden alcove",
			icon = "🌳",
			type = "visit_zone",
			target = 1,
			target_zone = "GardenAlcove",
			rewards = { gold = 70, tier_points = 14, items = {} },
			difficulty = 1,
			subtext = "Behind the old bakery, past the overgrown trellis, there's a hidden alcove where the first Zunda Peas were cultivated. The soil there still hums with ancient pea energy. FIND IT.",
		},
		{
			id = "quest_explore_well",
			name = "Well of Whispers",
			description = "Discover the Old Well",
			icon = "🪣",
			type = "visit_zone",
			target = 1,
			target_zone = "OldWell",
			rewards = { gold = 90, tier_points = 16, items = { "Zunda Root" } },
			difficulty = 2,
			subtext = "The Old Well at the village edge is more than it seems. Locals say if you drop a Zunda Pea in and listen carefully, you can hear the recipes of chefs long past. The well KNOWS things.",
			npc_dialogue = { speaker = "elder", lines = { "The Old Well... be careful near it. Some say it's bottomless. Some say it leads to THE KITCHEN BELOW.", "But if you listen close at midnight, you might hear the sound of perfect timing. Tick. Tock. COOK." } },
		},
		{
			id = "quest_explore_waterfall",
			name = "Cascade Kitchen",
			description = "Find the hidden waterfall cave",
			icon = "🌊",
			type = "visit_zone",
			target = 1,
			target_zone = "WaterfallCave",
			rewards = { gold = 140, tier_points = 22, items = { "Zunda Mushroom" } },
			difficulty = 2,
			subtext = "Behind the Great Waterfall lies a cave where Zunda monks aged their finest stews. The humidity. The cool air. The MUSHROOMS that glow in the dark. Some say the cave still holds a vat of 100-year-old stew...",
		},
		{
			id = "quest_explore_all",
			name = "Cartographer of Flavor",
			description = "Discover 10 unique locations",
			icon = "🗺️",
			type = "visit_zones_unique",
			target = 10,
			rewards = { gold = 500, tier_points = 75, items = { "Golden Harvest Platter" } },
			difficulty = 4,
			subtext = "Zunda Village is vast, and every corner hides a culinary secret. 10 locations. 10 stories. 10 chances to find ingredients no one else has touched. Become the Cartographer of Flavor. Map the delicious unknown.",
			npc_dialogue = { speaker = "narrator", lines = { "[ A scroll unfurls across the map table, revealing uncharted territories... ]", "[ Ink swirls into shapes: 'Here be ZUNDA PEAS.' The map is hungry for discovery. ]" } },
		},

		-- ── ECONOMY / GOLD QUESTS v2 ────────────────────────────────
		{
			id = "quest_gold_rush_1",
			name = "Pocket Change",
			description = "Earn 250 gold total",
			icon = "🪙",
			type = "earn_gold",
			target = 250,
			rewards = { gold = 30, tier_points = 10, items = {} },
			difficulty = 1,
			subtext = "Every gold coin starts with a single dish served. 250 gold might sound like pocket change to a Zunda veteran, but to a BEGINNER CHEF? It's the first step toward culinary empire.",
			chain_id = "gold_rush",
			chain_step = 1,
		},
		{
			id = "quest_gold_rush_2",
			name = "Gold Entree",
			description = "Accumulate 2,500 gold",
			icon = "💰",
			type = "earn_gold",
			target = 2500,
			rewards = { gold = 150, tier_points = 35, items = {} },
			difficulty = 3,
			subtext = "2500 gold. That's not pocket change anymore — that's a STEW FUND. The Zunda merchants start taking you seriously at this threshold. They might even show you the SECRET menu.",
			chain_id = "gold_rush",
			chain_step = 2,
		},
		{
			id = "quest_gold_rush_3",
			name = "Gold Rush Baron",
			description = "Accumulate 10,000 gold",
			icon = "💎",
			type = "earn_gold",
			target = 10000,
			rewards = { gold = 500, tier_points = 100, items = { "Ultimate Feast" } },
			difficulty = 5,
			subtext = "TEN THOUSAND GOLD. The stuff of Zunda LEGEND. Only the greatest chefs in Zunda Village history have reached this milestone. Your name will be carved into the Golden Spatula of Fame. FOREVER.",
			npc_dialogue = { speaker = "chef", lines = { "10,000 GOLD?!?!? I'VE BEEN COOKING FOR 40 YEARS AND I HAVEN'T REACHED THAT!!!", "...Who ARE you?!?! Are you THE CHOSEN ONE?!?! The Golden Pea Prophecy... it's REAL?!?!" } },
			chain_id = "gold_rush",
			chain_step = 3,
		},

		-- ── NEW COMPANION DISCOVERY QUESTS ────────────────────────────
		{
			id = "quest_meet_ankomon",
			name = "The Bean Awakening",
			description = "Summon Ankomon as your companion",
			icon = "🫘",
			type = "set_companion",
			target = 1,
			target_companion = "ankomon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A red bean spirit stirs in the pantry. Ankomon doesn't follow just ANYONE — he follows those who RESPECT THE BEAN. Set him as your companion and feel the PROTEIN POWER course through your kitchen.",
		},
		{
			id = "quest_meet_cardamon",
			name = "The Calm Before the Cook",
			description = "Summon Cardamon as your companion",
			icon = "🍋",
			type = "set_companion",
			target = 1,
			target_companion = "cardamon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A cardamom seedling spirit drifts through the herb garden. Cardamon brings PEACE to your kitchen. Set her as your companion and feel your perfect cooking window EXPAND.",
		},
		{
			id = "quest_meet_antimon",
			name = "The Speed Force",
			description = "Summon Antimon as your companion",
			icon = "🌿",
			type = "set_companion",
			target = 1,
			target_companion = "antimon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "A minty wisp zips past your stove. Antimon is PURE VELOCITY. Set him as your companion and unlock EXTRA DROPS from every gather. The kitchen will feel SLOW compared to him.",
		},
		{
			id = "quest_meet_sakuradamon",
			name = "Cherry Blossom Spirit",
			description = "Summon Sakuradamon as your companion",
			icon = "🌸",
			type = "set_companion",
			target = 1,
			target_companion = "sakuradamon",
			rewards = { gold = 100, tier_points = 20, items = {} },
			difficulty = 2,
			subtext = "Petals dance on the wind — Sakuradamon approaches. The blossom spirit carries knowledge of the old ways. Set her as your companion and gain +25% XP from everything you cook and serve.",
		},
	}
}
}

return QuestConfig