"""Zundamon cursor to Roblox Decal converter.
Place .ani/.cur files in Assets/Upload/Cursors/, then run this.
Output: PNG frames + Studio import script + CursorConfig.lua"""

import struct, os, io, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import ROOT

CURSOR_DIR = ROOT / "Assets" / "Upload" / "Cursors"
OUTPUT_DIR = ROOT / "Assets" / "Upload" / "Cursors" / "converted"

def convert_file_to_png(src_path: Path) -> list[Path]:
    """Convert cursor file to PNG(s). Uses PIL for .cur, generates stub for .ani."""
    results = []
    try:
        from PIL import Image
        ext = src_path.suffix.lower()
        if ext == ".cur":
            img = Image.open(src_path)
            png_path = OUTPUT_DIR / f"{src_path.stem}.png"
            img.save(png_path, "PNG")
            results.append(png_path)
        elif ext == ".ani":
            png_path = OUTPUT_DIR / f"{src_path.stem}.png"
            png_path.write_text("")  # placeholder
            results.append(png_path)
    except Exception as e:
        print(f"  Skip {src_path.name}: {e}")
    return results

def generate_import_script(png_files: list[Path]) -> str:
    """Generate a Studio command bar script to import PNGs as Decals."""
    lines = ["-- Generated by cursor_converter.py — Run in Studio command bar",
             "local results = {}",
             ""]
    for png in png_files:
        name = png.stem
        rel = png.relative_to(ROOT)
        lines.append(f"-- Import {name}")
        lines.append(f"local ok, decalId = pcall(function()")
        lines.append(f"    local decal = Instance.new('Decal')")
        lines.append(f"    decal.Name = '{name}_Cursor'")
        lines.append(f"    decal.Texture = 'rbxasset://{rel.as_posix()}'")
        lines.append(f"    return tostring(decal.Texture)")
        lines.append(f"end)")
        lines.append(f"if ok then")
        lines.append(f"    table.insert(results, {{ name = '{name}', decalId = decalId }})")
        lines.append(f"    print('Converted: {name} -> ' .. tostring(decalId))")
        lines.append(f"end")
        lines.append("")
    lines.append("print('=== RESULTS ===')")
    lines.append("print(game:GetService('HttpService'):JSONEncode(results))")
    return "\n".join(lines)

def generate_cursor_config(mapping: list[dict]) -> str:
    """Generate CursorConfig.lua with Roblox cursor mappings."""
    lines = ["--!strict",
             "-- [[ModuleScript] CursorConfig]",
             "-- Maps cursor names to uploaded Decal asset IDs",
             "-- Created by cursor_converter.py",
             "local CursorConfig = {",
             "    cursors = {",
             "        -- Zundamon themed cursors",
             "        -- Replace 'rbxassetid://0' with real uploaded Decal IDs",]
    for item in mapping:
        name = item.get("name", "unknown")
        lines.append(f"        ['{name}'] = 'rbxassetid://0',")
    lines.append("")
    lines.append("        -- Standard UI cursors")
    lines.append("        default = '',")
    lines.append("        pointing = '',")
    lines.append("        waiting = '',")
    lines.append("        text = '',")
    lines.append("    },")
    lines.append("}")
    lines.append("function CursorConfig.getCursor(name)")
    lines.append("    return CursorConfig.cursors[name] or ''")
    lines.append("end")
    lines.append("")
    lines.append("return CursorConfig")
    return "\n".join(lines)

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    print("=== Cursor Converter ===")

    all_pngs = []
    all_names = []
    for ext in ("*.ani", "*.cur"):
        for f in CURSOR_DIR.rglob(ext):
            if "converted" in f.parts: continue
            print(f"Found: {f.relative_to(CURSOR_DIR)}")
            all_names.append(f.stem)
            pngs = convert_file_to_png(f)
            all_pngs.extend(pngs)
            for p in pngs:
                print(f"  -> {p.name}")

    if not all_pngs:
        print("No .ani/.cur files found in Assets/Upload/Cursors/")
        print("Place them there first.")
        return

    import_script = generate_import_script(all_pngs)
    script_path = OUTPUT_DIR / "studio_import.luau"
    script_path.write_text(import_script, encoding="utf-8")
    print(f"\nImport script: {script_path}")

    config = generate_cursor_config([{"name": p.stem} for p in all_pngs])
    config_path = ROOT / "src" / "ReplicatedStorage" / "ConfigurationFiles" / "CursorConfig.lua"
    config_path.write_text(config, encoding="utf-8")
    print(f"Cursor config: {config_path}")
    print(f"\nDone. Output: {len(all_pngs)} PNGs")

if __name__ == "__main__":
    main()
