"""Live2D model preparation guide + frame extractor for VN portrait pipeline.
When expressions are rendered as PNGs, batch-import them as Decals and update VNDialoguePortraits."""

import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import ROOT

LIVE2D_SOURCE = Path("C:/Users/froma/Downloads/Live2D_VTubeStudio??????? 2/")

EXPRESSION_MAP = {
    "BrushFace": "happy",
    "ChangeGamingCon": "excited",
    "GameController": "excited",
    "GuruguruEye": "thinking",
    "Hauu": "embarrassed",
    "IndexFingerL": "pointing",
    "IndexFingerR": "pointing",
    "NoEyes": "sad",
    "PaleFace": "surprised",
    "ShockEye": "surprised",
    "SmallEyes": "suspicious",
    "StarEye": "amazed",
    "Sweat": "nervous",
    "Tear1": "crying",
    "Tear2": "crying",
    "WhiteEye": "deadpan",
}

MOTION_MAP = {
    "GamingController.motion3.json": "gaming",
    "Goo.motion3.json": "goo",
    "ShakeHandL.motion3.json": "wave_left",
    "ShakeHandR.motion3.json": "wave_right",
}

def print_guide():
    print("╔══════════════════════════════════════════════╗")
    print("║  Live2D → VN Portrait Pipeline              ║")
    print("╚══════════════════════════════════════════════╝")
    print()

    print("Step 1: Install Live2D Cubism Editor")
    print("  Download from: https://www.live2d.com/download/cubism/")
    print()

    print("Step 2: Open the Zundamon Live2D model")
    print(f"  File: {LIVE2D_SOURCE / 'zundamon.model3.json'}")
    print()

    print("Step 3: Render each expression as PNG")
    print("  In Cubism Editor, load each .exp3.json expression preset:")
    for exp_file, vn_expr in sorted(EXPRESSION_MAP.items()):
        print(f"    {exp_file:25s} → VN '{vn_expr}'")
    print()

    print("Step 4: Save rendered PNGs to Assets/Upload/Live2D/")
    print("  Then run: python scripts/agent_orchestrator/tools/live2d_prep.py --import")
    print()

    print("Step 5: Run the batch import")
    print("  npm run import:scan")
    print("  (paste script in Studio, save results)")
    print("  npm run import:apply")
    print("  → Auto-updates VNDialoguePortraits.lua")
    print()

    print("Alternative: Extract frames from built-in animations")
    print("  The .moc3 file contains all expression blend shapes.")
    print("  Use Cubism Viewer to preview and screenshot each expression.")
    print()

    print("18 expressions + 4 motion animations available.")

def generate_import_stub():
    lines = ["-- Generated by live2d_prep.py — Run after rendering expressions as PNGs",
             "-- Replace 'rbxassetid://0' with real imported Decal IDs",
             "",
             "-- VNDialoguePortraits.lua entry for live2d-based portraits:",
             "local VN_PORTRAITS = {",
             "    zundamon = {",
             "        full = 'rbxassetid://0',",
             "        face = 'rbxassetid://0',",
             "        body = 'rbxassetid://0',",
             "        expressions = {",]
    for vn_expr in sorted(set(EXPRESSION_MAP.values())):
        lines.append(f"            {vn_expr} = 'rbxassetid://0',")
    lines.append("        },",
                 "    },",
                 "}")
    return "\n".join(lines)

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--import", action="store_true", help="Generate import stub")
    args = parser.parse_args()

    if getattr(args, "import"):
        stub = generate_import_stub()
        stub_path = ROOT / "reports" / "mesh_pipeline" / "live2d_portraits_stub.lua"
        stub_path.parent.mkdir(parents=True, exist_ok=True)
        stub_path.write_text(stub, encoding="utf-8")
        print(f"Portrait stub written to: {stub_path}")
    else:
        print_guide()

if __name__ == "__main__":
    main()
