"""Automated mesh upload pipeline for Zundamon's Kitchen.
Handles: detection, upload via Open Cloud API, config update, Studio fallback."""

import json, os, sys, subprocess, tempfile, re
from pathlib import Path
from typing import Optional

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import ROOT

ASSETS_DIR = ROOT / "Assets"
GENERATED_DIR = ASSETS_DIR / "Generated"
UPLOAD_DIR = ASSETS_DIR / "Upload"

MESH_CONFIG_PATH = ROOT / "src" / "ReplicatedStorage" / "ConfigurationFiles" / "MeshAssets.lua"

class MeshPipeline:
    def __init__(self):
        self.results = {"uploaded": [], "failed": [], "skipped": []}

    def scan_source_files(self) -> list[dict]:
        """Scan Assets/ for OBJ/FBX files ready to upload."""
        files = []
        for ext in ("*.obj", "*.fbx", "*.glb", ".gltf"):
            for f in Path(ASSETS_DIR).rglob(ext):
                if f.stat().st_size > 0:
                    files.append({
                        "path": f,
                        "name": f.stem,
                        "ext": f.suffix.lower(),
                        "size_kb": f.stat().st_size / 1024,
                    })
        return files

    def read_pipeline_summary(self) -> dict:
        """Read the pipeline_summary.json for known asset IDs."""
        summary_path = GENERATED_DIR / "pipeline_summary.json"
        if summary_path.exists():
            try: return json.loads(summary_path.read_text(encoding="utf-8"))
            except: return {}
        return {}

    def generate_studio_import_script(self, mesh_files: list[dict]) -> str:
        """Generate a Luau script for Studio command bar to import all meshes."""
        lines = []
        lines.append("-- Generated by MeshPipeline - Run in Studio command bar")
        lines.append("-- Imports all detected mesh files and updates MeshAssets")
        lines.append("")
        lines.append("local AssetService = game:GetService('AssetService')")
        lines.append("local ReplicatedStorage = game:GetService('ReplicatedStorage')")
        lines.append("")
        lines.append("local meshFolder = Instance.new('Folder')")
        import time
        import_name = f"MeshImport_{int(time.time())}"
        lines.append(f"meshFolder.Name = '{import_name}'")
        lines.append("meshFolder.Parent = workspace")
        lines.append("")
        lines.append("local results = {}")
        for mf in mesh_files:
            name = mf["name"]
            rel = mf["path"].relative_to(ROOT)
            lines.append(f"")
            lines.append(f"-- Import {name}")
            lines.append(f"local ok, result = pcall(function()")
            lines.append(f"    local mesh = AssetService:CreateEditableMeshAsync(Content.fromUri('rbxasset://{rel.as_posix()}'))")
            lines.append(f"    local part = AssetService:CreateMeshPartAsync(Content.fromObject(mesh))")
            lines.append(f"    part.Name = '{name}'")
            lines.append(f"    part.Parent = meshFolder")
            lines.append(f"    return part.MeshId")
            lines.append(f"end)")
            lines.append(f"if ok then")
            lines.append(f"    table.insert(results, {{ name = '{name}', meshId = result }})")
            lines.append(f"    print('Imported: {name} -> ' .. result)")
            lines.append(f"else")
            lines.append(f"    warn('Failed: {name} -> ' .. tostring(result))")
            lines.append(f"end")
        lines.append("")
        lines.append("-- Output results as JSON for config update")
        lines.append("print('=== RESULTS ===')")
        lines.append("print(game:GetService('HttpService'):JSONEncode(results))")
        lines.append("print('=== END RESULTS ===')")
        return "\n".join(lines)

    def generate_update_commands(self, studio_results: list[dict]) -> str:
        """Generate admin commands to update configs with new asset IDs."""
        lines = []
        lines.append("-- Run these admin commands to update configs")
        lines.append("-- Press F2 in-game and paste each line")
        lines.append("")
        for r in studio_results:
            name = r.get("name", "")
            mesh_id = r.get("meshId", "")
            if mesh_id:
                lines.append(f"/updateconfig mesh.{name} {mesh_id}")
        return "\n".join(lines)

    def run(self, mode: str = "scan"):
        """Run the mesh pipeline."""
        print("=== Zunda Mesh Pipeline ===\n")

        # Phase 1: Scan for source files
        print("Phase 1: Scanning for source files...")
        files = self.scan_source_files()
        if files:
            print(f"  Found {len(files)} files:")
            for f in files:
                print(f"    {f['name']}{f['ext']} ({f['size_kb']:.1f} KB)")
        else:
            print("  No OBJ/FBX/GLB files found in Assets/")
            print("  Upload source files to:", ASSETS_DIR)
            print()

        # Phase 2: Read pipeline metadata
        print("\nPhase 2: Reading pipeline metadata...")
        summary = self.read_pipeline_summary()
        if summary and "asset_ids" in summary:
            ids = summary["asset_ids"]
            print(f"  {len(ids)} known asset IDs from pipeline")
            for name, aid in list(ids.items())[:5]:
                print(f"    {name}: {aid}")
            if len(ids) > 5:
                print(f"    ... and {len(ids)-5} more")
        else:
            print("  No pipeline summary found")

        # Phase 3: Generate Studio import script
        if files:
            output_dir = ROOT / "reports" / "mesh_pipeline"
            output_dir.mkdir(parents=True, exist_ok=True)

            print(f"\nPhase 3: Generating Studio import script...")
            script = self.generate_studio_import_script(files)
            script_path = output_dir / "studio_import.luau"
            script_path.write_text(script, encoding="utf-8")
            print(f"  Script written to: {script_path}")
            print(f"  Paste this into Studio command bar to import all meshes")

            print(f"\n=== Pipeline Complete ===")
            print(f"1. Copy the script: reports/mesh_pipeline/studio_import.luau")
            print(f"2. Paste into Studio command bar")
            print(f"3. Save Studio output JSON to: reports/mesh_pipeline/import_results.json")
            print(f"4. Auto-update configs: npm run import:apply")
            print(f"   Or: python scripts/agent_orchestrator/tools/batch_import.py --apply")
        else:
            print(f"\n=== No Files to Process ===")
            print(f"Place OBJ/FBX files in: {ASSETS_DIR / 'Upload'}")
            print(f"Or any subdirectory under: {ASSETS_DIR}")
            print(f"Then run: python scripts/agent_orchestrator/tools/mesh_pipeline.py")

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Zunda Mesh Pipeline")
    parser.add_argument("--mode", default="scan", choices=["scan", "upload"])
    args = parser.parse_args()
    MeshPipeline().run(args.mode)

if __name__ == "__main__":
    main()
